[build]
command = "bash scripts/netlify-build.sh"
publish = "dist"

[build.processing.html]
pretty_urls = false

[functions]
directory = "netlify/functions"

[[headers]]
for = "/_astro/*"

  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.xml"

  [headers.values]
  Cache-Control = "public, max-age=300, must-revalidate"
