title: 洪民憙雜記
languageNames:
  ko-Hang-KR: 한국어 (한글)
  ko-Kore: 朝鮮語 (國漢文)
authors:
- name:
    ko-Hang-KR: 홍민희
    ko-Kore: 洪民憙
  uri: https://hongminhee.org/
head: |
  <script defer
          data-domain="writings.hongminhee.org"
          src="https://plausible.io/js/plausible.js"></script>
