import { readFile, readdir } from "node:fs/promises";
import { join } from "node:path";
import manifest from "../netlify/edge-functions/content.generated.json" with { type: "json" };

const languageFiles = {
  en: "en",
  "ko-Hang-KR": "ko-hang-kr",
  "ko-Kore": "ko-kore",
  ja: "ja",
};

async function assertFile(path) {
  try {
    return await readFile(join("dist", path), "utf8");
  } catch (error) {
    throw new Error(`Expected build output is missing: dist/${path}`, {
      cause: error,
    });
  }
}

for (const [route, entry] of Object.entries(manifest)) {
  const directory = route === "/" ? "" : route.slice(1);
  await assertFile(`${directory}index.html`);
  for (const language of entry.languages) {
    await assertFile(`${directory}index.${languageFiles[language]}.html`);
  }
}

for (const language of Object.values(languageFiles)) {
  const feed = await assertFile(`feed.${language}.xml`);
  if (
    !feed.includes('<generator uri="https://astro.build/">Astro</generator>')
  ) {
    throw new Error(
      `feed.${language}.xml does not identify Astro as its generator`,
    );
  }
}

const exampleEnglish = await assertFile(
  "2026/03/legal-vs-legitimate/index.en.html",
);
if (!exampleEnglish.includes(">March 10, 2026</time>")) {
  throw new Error("Post dates are not being formatted in Asia/Seoul");
}
if (exampleEnglish.includes("//static/") || exampleEnglish.includes("Jikji")) {
  throw new Error(
    "Legacy asset URLs or generator metadata remain in post output",
  );
}

const exampleHangul = await assertFile(
  "2020/07/nobody-knows/index.ko-hang-kr.html",
);
if (!exampleHangul.includes("인공적 구조물에는")) {
  throw new Error(
    "The derived ko-Hang-KR representation was not generated by Seonbi",
  );
}

const exampleMixed = await assertFile(
  "2020/07/nobody-knows/index.ko-kore.html",
);
if (!exampleMixed.includes('<html lang="ko-Kore" class="vertical">')) {
  throw new Error(
    "The ko-Kore representation is no longer vertical by default",
  );
}
if (!exampleMixed.includes('<div class="languages">')) {
  throw new Error(
    "The post language selector no longer uses the legacy layout structure",
  );
}

async function walk(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  return (
    await Promise.all(
      entries.map((entry) => {
        const path = join(directory, entry.name);
        return entry.isDirectory() ? walk(path) : path;
      }),
    )
  ).flat();
}

const legacyOutputs = (await walk("dist")).filter(
  (path) => path.endsWith(".php") || path.endsWith(".etag"),
);
if (legacyOutputs.length > 0) {
  throw new Error(
    `Legacy PHP or ETag sidecars were generated: ${legacyOutputs.join(", ")}`,
  );
}
