name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - run: sudo apt-get install -y git-restore-mtime sassc
    - run: git restore-mtime
    - uses: actions/cache@v2
      with:
        key: deno
        path: |
          ${{ github.workspace }}/.bin
          ${{ github.workspace }}/.deno
    - run: |
        deno cache \
          --import-map import_map.json \
          --reload \
          --lock=lock.json \
          main.ts
    - run: |
        deno run \
          --allow-all \
          --import-map import_map.json \
          --lock=lock.json \
          --cached-only \
          main.ts \
            -u "$BASE_URL" \
            $EXTRA_ARGS
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        EXTRA_ARGS: ${{ secrets.EXTRA_ARGS }}
    - uses: sand4rt/ftp-deployer@v1.3
      with:
        sftp: true
        port: 22
        host: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        remote_folder: ${{ secrets.FTP_REMOTE_DIR }}
        local_folder: public_html
        cleanup: true
    - uses: chetan/invalidate-cloudfront-action@v2
      env:
        DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
        PATHS: "/*"
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - uses: actions/upload-artifact@v2
      with:
        name: public_html
        path: public_html/